language: java
jdk:
  - openjdk8
sudo: false
before_script:
  - chmod +x gradlew
  - pip install --user codecov
script:
  - ./gradlew check
after_success:
  - codecov
install:
- ./gradlew assemble --info